#ifndef CRYPTO_ASYMMETRIC_CIPHER_H
#define CRYPTO_ASYMMETRIC_CIPHER_H

#include "Util.h"

typedef struct { CRYPTO_BIGNUM N; CRYPTO_BIGNUM E; } CRYPTO_RSA_PUBLIC_KEY;
typedef struct { CRYPTO_BIGNUM N; CRYPTO_BIGNUM D; CRYPTO_BIGNUM P; CRYPTO_BIGNUM Q; } CRYPTO_RSA_PRIVATE_KEY;
typedef struct { CRYPTO_BIGNUM P; CRYPTO_BIGNUM Q; CRYPTO_BIGNUM G; CRYPTO_BIGNUM H; } CRYPTO_ELGAMAL_PUBLIC_KEY;
typedef struct { CRYPTO_BIGNUM X; } CRYPTO_ELGAMAL_PRIVATE_KEY;
typedef struct { CRYPTO_BIGNUM C1; CRYPTO_BIGNUM C2; } CRYPTO_ELGAMAL_CIPHERTEXT;

CRYPTO_BEGIN_DECLS
CRYPTO_API void CRYPTO_RSA_PUBLIC_KEY_INIT(CRYPTO_RSA_PUBLIC_KEY *KEY);
CRYPTO_API void CRYPTO_RSA_PUBLIC_KEY_FREE(CRYPTO_RSA_PUBLIC_KEY *KEY);
CRYPTO_API void CRYPTO_RSA_PRIVATE_KEY_INIT(CRYPTO_RSA_PRIVATE_KEY *KEY);
CRYPTO_API void CRYPTO_RSA_PRIVATE_KEY_FREE(CRYPTO_RSA_PRIVATE_KEY *KEY);
CRYPTO_API CryptoError CRYPTO_RSA_KEYGEN(CRYPTO_RSA_PUBLIC_KEY *PUBLIC_KEY, CRYPTO_RSA_PRIVATE_KEY *PRIVATE_KEY, size_t MODULUS_BITS, uint32_t PRIME_ROUNDS, AlgID ALG);
CRYPTO_API CryptoError CRYPTO_RSA_ENCRYPT(CRYPTO_BIGNUM *CIPHERTEXT, const CRYPTO_BIGNUM *MESSAGE, const CRYPTO_RSA_PUBLIC_KEY *PUBLIC_KEY, AlgID ALG);
CRYPTO_API CryptoError CRYPTO_RSA_DECRYPT(CRYPTO_BIGNUM *MESSAGE, const CRYPTO_BIGNUM *CIPHERTEXT, const CRYPTO_RSA_PRIVATE_KEY *PRIVATE_KEY, AlgID ALG);

CRYPTO_API void CRYPTO_ELGAMAL_PUBLIC_KEY_INIT(CRYPTO_ELGAMAL_PUBLIC_KEY *KEY);
CRYPTO_API void CRYPTO_ELGAMAL_PUBLIC_KEY_FREE(CRYPTO_ELGAMAL_PUBLIC_KEY *KEY);
CRYPTO_API void CRYPTO_ELGAMAL_PRIVATE_KEY_INIT(CRYPTO_ELGAMAL_PRIVATE_KEY *KEY);
CRYPTO_API void CRYPTO_ELGAMAL_PRIVATE_KEY_FREE(CRYPTO_ELGAMAL_PRIVATE_KEY *KEY);
CRYPTO_API void CRYPTO_ELGAMAL_CIPHERTEXT_INIT(CRYPTO_ELGAMAL_CIPHERTEXT *CIPHERTEXT);
CRYPTO_API void CRYPTO_ELGAMAL_CIPHERTEXT_FREE(CRYPTO_ELGAMAL_CIPHERTEXT *CIPHERTEXT);
CRYPTO_API CryptoError CRYPTO_ELGAMAL_KEYGEN(CRYPTO_ELGAMAL_PUBLIC_KEY *PUBLIC_KEY, CRYPTO_ELGAMAL_PRIVATE_KEY *PRIVATE_KEY, size_t MODULUS_BITS, uint32_t PRIME_ROUNDS, AlgID ALG);
CRYPTO_API CryptoError CRYPTO_ELGAMAL_ENCRYPT(CRYPTO_ELGAMAL_CIPHERTEXT *CIPHERTEXT, const CRYPTO_BIGNUM *MESSAGE, const CRYPTO_ELGAMAL_PUBLIC_KEY *PUBLIC_KEY, AlgID ALG);
CRYPTO_API CryptoError CRYPTO_ELGAMAL_DECRYPT(CRYPTO_BIGNUM *MESSAGE, const CRYPTO_ELGAMAL_CIPHERTEXT *CIPHERTEXT, const CRYPTO_ELGAMAL_PUBLIC_KEY *PUBLIC_KEY, const CRYPTO_ELGAMAL_PRIVATE_KEY *PRIVATE_KEY, AlgID ALG);
CRYPTO_END_DECLS

#endif
