#ifndef CRYPTO_DIGITAL_SIGNATURE_H
#define CRYPTO_DIGITAL_SIGNATURE_H

#include "Def.h"

#define CRYPTO_SIGNATURE_CONTEXT_MAX_BYTES 255u

#define CRYPTO_ML_DSA_44_PUBLIC_KEY_BYTES 1312u
#define CRYPTO_ML_DSA_44_PRIVATE_KEY_BYTES 2560u
#define CRYPTO_ML_DSA_44_SIGNATURE_BYTES 2420u
#define CRYPTO_ML_DSA_65_PUBLIC_KEY_BYTES 1952u
#define CRYPTO_ML_DSA_65_PRIVATE_KEY_BYTES 4032u
#define CRYPTO_ML_DSA_65_SIGNATURE_BYTES 3309u
#define CRYPTO_ML_DSA_87_PUBLIC_KEY_BYTES 2592u
#define CRYPTO_ML_DSA_87_PRIVATE_KEY_BYTES 4896u
#define CRYPTO_ML_DSA_87_SIGNATURE_BYTES 4627u

#define CRYPTO_SLH_DSA_128_PUBLIC_KEY_BYTES 32u
#define CRYPTO_SLH_DSA_128_PRIVATE_KEY_BYTES 64u
#define CRYPTO_SLH_DSA_128S_SIGNATURE_BYTES 7856u
#define CRYPTO_SLH_DSA_128F_SIGNATURE_BYTES 17088u
#define CRYPTO_SLH_DSA_192_PUBLIC_KEY_BYTES 48u
#define CRYPTO_SLH_DSA_192_PRIVATE_KEY_BYTES 96u
#define CRYPTO_SLH_DSA_192S_SIGNATURE_BYTES 16224u
#define CRYPTO_SLH_DSA_192F_SIGNATURE_BYTES 35664u
#define CRYPTO_SLH_DSA_256_PUBLIC_KEY_BYTES 64u
#define CRYPTO_SLH_DSA_256_PRIVATE_KEY_BYTES 128u
#define CRYPTO_SLH_DSA_256S_SIGNATURE_BYTES 29792u
#define CRYPTO_SLH_DSA_256F_SIGNATURE_BYTES 49856u

CRYPTO_BEGIN_DECLS
CRYPTO_API size_t CRYPTO_ML_DSA_PUBLIC_KEY_SIZE(AlgID ALG);
CRYPTO_API size_t CRYPTO_ML_DSA_PRIVATE_KEY_SIZE(AlgID ALG);
CRYPTO_API size_t CRYPTO_ML_DSA_SIGNATURE_SIZE(AlgID ALG);
CRYPTO_API CryptoError CRYPTO_ML_DSA_KEYGEN(uint8_t *PUBLIC_KEY, size_t PUBLIC_KEY_LENGTH, uint8_t *PRIVATE_KEY, size_t PRIVATE_KEY_LENGTH, AlgID ALG);
CRYPTO_API CryptoError CRYPTO_ML_DSA_SIGN(const uint8_t *PRIVATE_KEY, size_t PRIVATE_KEY_LENGTH, const uint8_t *MESSAGE, size_t MESSAGE_LENGTH, const uint8_t *CONTEXT, size_t CONTEXT_LENGTH, uint8_t *SIGNATURE, size_t SIGNATURE_LENGTH, AlgID ALG);
CRYPTO_API CryptoError CRYPTO_ML_DSA_VERIFY(const uint8_t *PUBLIC_KEY, size_t PUBLIC_KEY_LENGTH, const uint8_t *MESSAGE, size_t MESSAGE_LENGTH, const uint8_t *CONTEXT, size_t CONTEXT_LENGTH, const uint8_t *SIGNATURE, size_t SIGNATURE_LENGTH, AlgID ALG);

CRYPTO_API size_t CRYPTO_SLH_DSA_PUBLIC_KEY_SIZE(AlgID ALG);
CRYPTO_API size_t CRYPTO_SLH_DSA_PRIVATE_KEY_SIZE(AlgID ALG);
CRYPTO_API size_t CRYPTO_SLH_DSA_SIGNATURE_SIZE(AlgID ALG);
CRYPTO_API CryptoError CRYPTO_SLH_DSA_KEYGEN(uint8_t *PUBLIC_KEY, size_t PUBLIC_KEY_LENGTH, uint8_t *PRIVATE_KEY, size_t PRIVATE_KEY_LENGTH, AlgID ALG);
CRYPTO_API CryptoError CRYPTO_SLH_DSA_SIGN(const uint8_t *PRIVATE_KEY, size_t PRIVATE_KEY_LENGTH, const uint8_t *MESSAGE, size_t MESSAGE_LENGTH, const uint8_t *CONTEXT, size_t CONTEXT_LENGTH, uint8_t *SIGNATURE, size_t SIGNATURE_LENGTH, AlgID ALG);
CRYPTO_API CryptoError CRYPTO_SLH_DSA_VERIFY(const uint8_t *PUBLIC_KEY, size_t PUBLIC_KEY_LENGTH, const uint8_t *MESSAGE, size_t MESSAGE_LENGTH, const uint8_t *CONTEXT, size_t CONTEXT_LENGTH, const uint8_t *SIGNATURE, size_t SIGNATURE_LENGTH, AlgID ALG);
CRYPTO_END_DECLS

#endif
