#ifndef CRYPTO_KEY_ENCAPSULATION_H
#define CRYPTO_KEY_ENCAPSULATION_H

#include "Def.h"

#define CRYPTO_ML_KEM_512_PUBLIC_KEY_BYTES 800u
#define CRYPTO_ML_KEM_512_PRIVATE_KEY_BYTES 1632u
#define CRYPTO_ML_KEM_512_CIPHERTEXT_BYTES 768u
#define CRYPTO_ML_KEM_768_PUBLIC_KEY_BYTES 1184u
#define CRYPTO_ML_KEM_768_PRIVATE_KEY_BYTES 2400u
#define CRYPTO_ML_KEM_768_CIPHERTEXT_BYTES 1088u
#define CRYPTO_ML_KEM_1024_PUBLIC_KEY_BYTES 1568u
#define CRYPTO_ML_KEM_1024_PRIVATE_KEY_BYTES 3168u
#define CRYPTO_ML_KEM_1024_CIPHERTEXT_BYTES 1568u
#define CRYPTO_ML_KEM_SHARED_SECRET_BYTES 32u

CRYPTO_BEGIN_DECLS
CRYPTO_API size_t CRYPTO_ML_KEM_PUBLIC_KEY_SIZE(AlgID ALG);
CRYPTO_API size_t CRYPTO_ML_KEM_PRIVATE_KEY_SIZE(AlgID ALG);
CRYPTO_API size_t CRYPTO_ML_KEM_CIPHERTEXT_SIZE(AlgID ALG);
CRYPTO_API CryptoError CRYPTO_ML_KEM_KEYGEN(uint8_t *PUBLIC_KEY, size_t PUBLIC_KEY_LENGTH, uint8_t *PRIVATE_KEY, size_t PRIVATE_KEY_LENGTH, AlgID ALG);
CRYPTO_API CryptoError CRYPTO_ML_KEM_ENCAPS(const uint8_t *PUBLIC_KEY, size_t PUBLIC_KEY_LENGTH, uint8_t SHARED_SECRET[CRYPTO_ML_KEM_SHARED_SECRET_BYTES], uint8_t *CIPHERTEXT, size_t CIPHERTEXT_LENGTH, AlgID ALG);
CRYPTO_API CryptoError CRYPTO_ML_KEM_DECAPS(const uint8_t *PRIVATE_KEY, size_t PRIVATE_KEY_LENGTH, const uint8_t *CIPHERTEXT, size_t CIPHERTEXT_LENGTH, uint8_t SHARED_SECRET[CRYPTO_ML_KEM_SHARED_SECRET_BYTES], AlgID ALG);
CRYPTO_END_DECLS

#endif
