#ifndef CRYPTO_RANDOM_NUMBER_GENERATION_H
#define CRYPTO_RANDOM_NUMBER_GENERATION_H

#include "Def.h"

#define CRYPTO_CTR_DRBG_BLOCK_BYTES 16u
#define CRYPTO_CTR_DRBG_MAX_KEY_BYTES 32u
#define CRYPTO_CTR_DRBG_MAX_SEED_BYTES 48u
#define CRYPTO_CTR_DRBG_MAX_REQUEST_BYTES 65536u

typedef struct {
    AlgID ALG;
    uint8_t KEY[CRYPTO_CTR_DRBG_MAX_KEY_BYTES];
    uint8_t V[CRYPTO_CTR_DRBG_BLOCK_BYTES];
    uint64_t RESEED_COUNTER;
    uint8_t KEY_LENGTH;
    uint8_t USE_DF;
    uint8_t INSTANTIATED;
} CRYPTO_CTR_DRBG_CONTEXT;

CRYPTO_BEGIN_DECLS
CRYPTO_API CryptoError CRYPTO_RANDOM_BYTES(uint8_t *OUTPUT, size_t OUTPUT_LENGTH);
CRYPTO_API size_t CRYPTO_CTR_DRBG_SEED_SIZE(AlgID ALG);
CRYPTO_API CryptoError CRYPTO_CTR_DRBG_INSTANTIATE(
    CRYPTO_CTR_DRBG_CONTEXT *CONTEXT,
    const uint8_t *ENTROPY, size_t ENTROPY_LENGTH,
    const uint8_t *NONCE, size_t NONCE_LENGTH,
    const uint8_t *PERSONALIZATION, size_t PERSONALIZATION_LENGTH,
    AlgID ALG);
CRYPTO_API CryptoError CRYPTO_CTR_DRBG_INSTANTIATE_OS(
    CRYPTO_CTR_DRBG_CONTEXT *CONTEXT,
    const uint8_t *PERSONALIZATION, size_t PERSONALIZATION_LENGTH,
    AlgID ALG);
CRYPTO_API CryptoError CRYPTO_CTR_DRBG_RESEED(
    CRYPTO_CTR_DRBG_CONTEXT *CONTEXT,
    const uint8_t *ENTROPY, size_t ENTROPY_LENGTH,
    const uint8_t *ADDITIONAL, size_t ADDITIONAL_LENGTH);
CRYPTO_API CryptoError CRYPTO_CTR_DRBG_RESEED_OS(
    CRYPTO_CTR_DRBG_CONTEXT *CONTEXT,
    const uint8_t *ADDITIONAL, size_t ADDITIONAL_LENGTH);
CRYPTO_API CryptoError CRYPTO_CTR_DRBG_GENERATE(
    CRYPTO_CTR_DRBG_CONTEXT *CONTEXT,
    uint8_t *OUTPUT, size_t OUTPUT_LENGTH,
    const uint8_t *ADDITIONAL, size_t ADDITIONAL_LENGTH,
    int PREDICTION_RESISTANCE);
CRYPTO_API void CRYPTO_CTR_DRBG_CLEAR(CRYPTO_CTR_DRBG_CONTEXT *CONTEXT);
CRYPTO_END_DECLS

#endif
