#ifndef CRYPTO_UTIL_H
#define CRYPTO_UTIL_H

#include "Def.h"

typedef struct {
    uint32_t *LIMBS;
    size_t LENGTH;
    size_t CAPACITY;
} CRYPTO_BIGNUM;

CRYPTO_BEGIN_DECLS
CRYPTO_API void CRYPTO_BIGNUM_INIT(CRYPTO_BIGNUM *VALUE);
CRYPTO_API void CRYPTO_BIGNUM_FREE(CRYPTO_BIGNUM *VALUE);
CRYPTO_API CryptoError CRYPTO_BIGNUM_FROM_BYTES_BE(CRYPTO_BIGNUM *OUTPUT, const uint8_t *BYTES, size_t LENGTH);
CRYPTO_API CryptoError CRYPTO_BIGNUM_FROM_BYTES_LE(CRYPTO_BIGNUM *OUTPUT, const uint8_t *BYTES, size_t LENGTH);
CRYPTO_API CryptoError CRYPTO_BIGNUM_TO_BYTES_BE(const CRYPTO_BIGNUM *INPUT, uint8_t *OUTPUT, size_t OUTPUT_LENGTH);
CRYPTO_API CryptoError CRYPTO_BIGNUM_TO_BYTES_LE(const CRYPTO_BIGNUM *INPUT, uint8_t *OUTPUT, size_t OUTPUT_LENGTH);
CRYPTO_API int CRYPTO_PRIME_IS_PROBABLE(const CRYPTO_BIGNUM *VALUE, uint32_t ROUNDS);
CRYPTO_API CryptoError CRYPTO_PRIME_GENERATE(CRYPTO_BIGNUM *OUTPUT, size_t BITS, uint32_t ROUNDS);
CRYPTO_API CryptoError CRYPTO_PRIME_GENERATE_SAFE(CRYPTO_BIGNUM *P, CRYPTO_BIGNUM *Q, size_t P_BITS, uint32_t ROUNDS);
CRYPTO_END_DECLS

#endif
