/*
 * Runtime parameters for NTRU+.
 * Derived from the NTRU+ reference implementation.
 * SPDX-License-Identifier: MIT
 */

#ifndef CRYPTO_NTRU_PLUS_PARAMETER_H
#define CRYPTO_NTRU_PLUS_PARAMETER_H

#include "Def.h"

#define CRYPTO_NTRU_PLUS_Q 3457
#define CRYPTO_NTRU_PLUS_SEED_BYTES 32u
#define LIBERAC_NTRU_PLUS_SHARED_SECRET_BYTES 32u

#define CRYPTO_NTRU_PLUS_768_N 768u
#define CRYPTO_NTRU_PLUS_768_BASE_DEGREE 4u
#define CRYPTO_NTRU_PLUS_768_POLYNOMIAL_BYTES 1152u
#define LIBERAC_NTRU_PLUS_768_PUBLIC_KEY_BYTES 1152u
#define LIBERAC_NTRU_PLUS_768_PRIVATE_KEY_BYTES 2336u
#define LIBERAC_NTRU_PLUS_768_CIPHERTEXT_BYTES 1152u

#define CRYPTO_NTRU_PLUS_864_N 864u
#define CRYPTO_NTRU_PLUS_864_BASE_DEGREE 3u
#define CRYPTO_NTRU_PLUS_864_POLYNOMIAL_BYTES 1296u
#define LIBERAC_NTRU_PLUS_864_PUBLIC_KEY_BYTES 1296u
#define LIBERAC_NTRU_PLUS_864_PRIVATE_KEY_BYTES 2624u
#define LIBERAC_NTRU_PLUS_864_CIPHERTEXT_BYTES 1296u

#define CRYPTO_NTRU_PLUS_1152_N 1152u
#define CRYPTO_NTRU_PLUS_1152_BASE_DEGREE 4u
#define CRYPTO_NTRU_PLUS_1152_POLYNOMIAL_BYTES 1728u
#define LIBERAC_NTRU_PLUS_1152_PUBLIC_KEY_BYTES 1728u
#define LIBERAC_NTRU_PLUS_1152_PRIVATE_KEY_BYTES 3488u
#define LIBERAC_NTRU_PLUS_1152_CIPHERTEXT_BYTES 1728u

#define CRYPTO_NTRU_PLUS_MAX_N CRYPTO_NTRU_PLUS_1152_N
#define CRYPTO_NTRU_PLUS_MAX_POLYNOMIAL_BYTES \
    CRYPTO_NTRU_PLUS_1152_POLYNOMIAL_BYTES
#define CRYPTO_NTRU_PLUS_MAX_PRIVATE_KEY_BYTES \
    LIBERAC_NTRU_PLUS_1152_PRIVATE_KEY_BYTES

typedef struct crypto_ntru_plus_parameters {
    LiberaCAlgID alg;
    size_t n;
    size_t base_degree;
    size_t polynomial_bytes;
    size_t public_key_bytes;
    size_t private_key_bytes;
    size_t ciphertext_bytes;
} crypto_ntru_plus_parameters;

const crypto_ntru_plus_parameters *crypto_ntru_plus_parameters_for(LiberaCAlgID alg);

#endif
