#ifndef CRYPTO_BIGNUM_H
#define CRYPTO_BIGNUM_H

#include "TYPES.h"
#include "ERROR.h"
#include "CRYPTO_EXPORT.h"

typedef struct {
    uint32_t *LIMBS;
    size_t LENGTH;
    size_t CAPACITY;
} BIGNUM;

CRYPTO_API void BIGNUM_INIT(BIGNUM *VALUE);
CRYPTO_API void BIGNUM_FREE(BIGNUM *VALUE);
CRYPTO_API CryptoError BIGNUM_COPY(BIGNUM *OUT, const BIGNUM *IN);
CRYPTO_API CryptoError BIGNUM_SET_U64(BIGNUM *OUT, uint64_t VALUE);
CRYPTO_API CryptoError BIGNUM_FROM_BYTES_BE(BIGNUM *OUT, const uint8_t *BYTES, size_t LENGTH);
CRYPTO_API CryptoError BIGNUM_FROM_BYTES_LE(BIGNUM *OUT, const uint8_t *BYTES, size_t LENGTH);
CRYPTO_API CryptoError BIGNUM_TO_BYTES_BE(const BIGNUM *IN, uint8_t *OUT, size_t OUT_LENGTH);
CRYPTO_API CryptoError BIGNUM_TO_BYTES_LE(const BIGNUM *IN, uint8_t *OUT, size_t OUT_LENGTH);
CRYPTO_API size_t BIGNUM_BYTE_LENGTH(const BIGNUM *VALUE);
CRYPTO_API size_t BIGNUM_BIT_LENGTH(const BIGNUM *VALUE);
CRYPTO_API int BIGNUM_COMPARE(const BIGNUM *A, const BIGNUM *B);
CRYPTO_API int BIGNUM_IS_ZERO(const BIGNUM *VALUE);
CRYPTO_API CryptoError BIGNUM_ADD(BIGNUM *OUT, const BIGNUM *A, const BIGNUM *B);
CRYPTO_API CryptoError BIGNUM_SUB(BIGNUM *OUT, const BIGNUM *A, const BIGNUM *B);
CRYPTO_API CryptoError BIGNUM_MUL(BIGNUM *OUT, const BIGNUM *A, const BIGNUM *B);
CRYPTO_API CryptoError BIGNUM_MOD(BIGNUM *OUT, const BIGNUM *A, const BIGNUM *MODULUS);
CRYPTO_API CryptoError BIGNUM_MOD_MUL(BIGNUM *OUT, const BIGNUM *A, const BIGNUM *B, const BIGNUM *MODULUS);
CRYPTO_API CryptoError BIGNUM_MOD_EXP(BIGNUM *OUT, const BIGNUM *BASE, const BIGNUM *EXPONENT, const BIGNUM *MODULUS);
CRYPTO_API CryptoError BIGNUM_RANDOM_BITS(BIGNUM *OUT, size_t BITS, int SET_TOP_BIT, int SET_ODD);
CRYPTO_API CryptoError BIGNUM_RANDOM_RANGE(BIGNUM *OUT, const BIGNUM *UPPER_EXCLUSIVE);

#endif
