#ifndef CRYPTO_ELGAMAL_H
#define CRYPTO_ELGAMAL_H

#include "TYPES.h"
#include "ALGID.h"
#include "ERROR.h"
#include "BIGNUM.h"
#include "CRYPTO_EXPORT.h"

typedef struct { BIGNUM P; BIGNUM Q; BIGNUM G; BIGNUM H; } ELGAMAL_PUBLIC_KEY;
typedef struct { BIGNUM X; } ELGAMAL_PRIVATE_KEY;
typedef struct { BIGNUM C1; BIGNUM C2; } ELGAMAL_CIPHERTEXT;

CRYPTO_API void ELGAMAL_PUBLIC_KEY_INIT(ELGAMAL_PUBLIC_KEY *KEY);
CRYPTO_API void ELGAMAL_PUBLIC_KEY_FREE(ELGAMAL_PUBLIC_KEY *KEY);
CRYPTO_API void ELGAMAL_PRIVATE_KEY_INIT(ELGAMAL_PRIVATE_KEY *KEY);
CRYPTO_API void ELGAMAL_PRIVATE_KEY_FREE(ELGAMAL_PRIVATE_KEY *KEY);
CRYPTO_API void ELGAMAL_CIPHERTEXT_INIT(ELGAMAL_CIPHERTEXT *CIPHERTEXT);
CRYPTO_API void ELGAMAL_CIPHERTEXT_FREE(ELGAMAL_CIPHERTEXT *CIPHERTEXT);
CRYPTO_API CryptoError ELGAMAL_KEYGEN(AlgID ALG, ELGAMAL_PUBLIC_KEY *PUBLIC_KEY, ELGAMAL_PRIVATE_KEY *PRIVATE_KEY, size_t MODULUS_BITS, uint32_t PRIME_ROUNDS);
CRYPTO_API CryptoError ELGAMAL_ENCRYPT(AlgID ALG, ELGAMAL_CIPHERTEXT *CIPHERTEXT, const BIGNUM *MESSAGE, const ELGAMAL_PUBLIC_KEY *PUBLIC_KEY);
CRYPTO_API CryptoError ELGAMAL_DECRYPT(AlgID ALG, BIGNUM *MESSAGE, const ELGAMAL_CIPHERTEXT *CIPHERTEXT, const ELGAMAL_PUBLIC_KEY *PUBLIC_KEY, const ELGAMAL_PRIVATE_KEY *PRIVATE_KEY);

#endif
