#ifndef CRYPTO_ERROR_H
#define CRYPTO_ERROR_H

#include "CRYPTO_EXPORT.h"

typedef int CryptoError;

enum {
    CRYPTO_SUCCESS = 0,
    CRYPTO_ERROR_INVALID_ARGUMENT = -1,
    CRYPTO_ERROR_INVALID_ALG_ID = -2,
    CRYPTO_ERROR_UNSUPPORTED_ALGORITHM = -3,
    CRYPTO_ERROR_BUFFER_TOO_SMALL = -4,
    CRYPTO_ERROR_ALLOCATION_FAILED = -5,
    CRYPTO_ERROR_RANDOM_FAILED = -6,
    CRYPTO_ERROR_INVALID_KEY = -7,
    CRYPTO_ERROR_MESSAGE_TOO_LARGE = -8,
    CRYPTO_ERROR_PRIME_GENERATION_FAILED = -9,
    CRYPTO_ERROR_ARITHMETIC = -10,
    CRYPTO_ERROR_INTERNAL = -11,
    CRYPTO_ERROR_AUTHENTICATION_FAILED = -12,
    CRYPTO_ERROR_RESEED_REQUIRED = -13,
    CRYPTO_ERROR_SIGNATURE_INVALID = -14
};

CRYPTO_API const char *CRYPTO_ERROR_STRING(CryptoError ERROR);

#endif
