#ifndef CRYPTO_ML_DSA_H
#define CRYPTO_ML_DSA_H

#include "TYPES.h"
#include "ALGID.h"
#include "ERROR.h"
#include "CRYPTO_EXPORT.h"

#define ML_DSA_CONTEXT_MAX_BYTES 255u
#define ML_DSA_44_PUBLIC_KEY_BYTES 1312u
#define ML_DSA_44_PRIVATE_KEY_BYTES 2560u
#define ML_DSA_44_SIGNATURE_BYTES 2420u
#define ML_DSA_65_PUBLIC_KEY_BYTES 1952u
#define ML_DSA_65_PRIVATE_KEY_BYTES 4032u
#define ML_DSA_65_SIGNATURE_BYTES 3309u
#define ML_DSA_87_PUBLIC_KEY_BYTES 2592u
#define ML_DSA_87_PRIVATE_KEY_BYTES 4896u
#define ML_DSA_87_SIGNATURE_BYTES 4627u

CRYPTO_API size_t ML_DSA_PUBLIC_KEY_SIZE(AlgID ALG);
CRYPTO_API size_t ML_DSA_PRIVATE_KEY_SIZE(AlgID ALG);
CRYPTO_API size_t ML_DSA_SIGNATURE_SIZE(AlgID ALG);

CRYPTO_API CryptoError ML_DSA_KEYGEN(
    AlgID ALG,
    uint8_t *PUBLIC_KEY, size_t PUBLIC_KEY_LENGTH,
    uint8_t *PRIVATE_KEY, size_t PRIVATE_KEY_LENGTH);

CRYPTO_API CryptoError ML_DSA_SIGN(
    AlgID ALG,
    const uint8_t *PRIVATE_KEY, size_t PRIVATE_KEY_LENGTH,
    const uint8_t *MESSAGE, size_t MESSAGE_LENGTH,
    const uint8_t *CONTEXT, size_t CONTEXT_LENGTH,
    uint8_t *SIGNATURE, size_t SIGNATURE_LENGTH);

CRYPTO_API CryptoError ML_DSA_VERIFY(
    AlgID ALG,
    const uint8_t *PUBLIC_KEY, size_t PUBLIC_KEY_LENGTH,
    const uint8_t *MESSAGE, size_t MESSAGE_LENGTH,
    const uint8_t *CONTEXT, size_t CONTEXT_LENGTH,
    const uint8_t *SIGNATURE, size_t SIGNATURE_LENGTH);

#endif
