#ifndef CRYPTO_RSA_H
#define CRYPTO_RSA_H

#include "TYPES.h"
#include "ALGID.h"
#include "ERROR.h"
#include "BIGNUM.h"
#include "CRYPTO_EXPORT.h"

typedef struct { BIGNUM N; BIGNUM E; } RSA_PUBLIC_KEY;
typedef struct { BIGNUM N; BIGNUM D; BIGNUM P; BIGNUM Q; } RSA_PRIVATE_KEY;

CRYPTO_API void CRYPTO_RSA_PUBLIC_KEY_INIT(RSA_PUBLIC_KEY *KEY);
CRYPTO_API void CRYPTO_RSA_PUBLIC_KEY_FREE(RSA_PUBLIC_KEY *KEY);
CRYPTO_API void CRYPTO_RSA_PRIVATE_KEY_INIT(RSA_PRIVATE_KEY *KEY);
CRYPTO_API void CRYPTO_RSA_PRIVATE_KEY_FREE(RSA_PRIVATE_KEY *KEY);
CRYPTO_API CryptoError CRYPTO_RSA_KEYGEN(AlgID ALG, RSA_PUBLIC_KEY *PUBLIC_KEY, RSA_PRIVATE_KEY *PRIVATE_KEY, size_t MODULUS_BITS, uint32_t PRIME_ROUNDS);
CRYPTO_API CryptoError CRYPTO_RSA_ENCRYPT(AlgID ALG, BIGNUM *CIPHERTEXT, const BIGNUM *MESSAGE, const RSA_PUBLIC_KEY *PUBLIC_KEY);
CRYPTO_API CryptoError CRYPTO_RSA_DECRYPT(AlgID ALG, BIGNUM *MESSAGE, const BIGNUM *CIPHERTEXT, const RSA_PRIVATE_KEY *PRIVATE_KEY);

#endif
